/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingsRouteImport } from './routes/weddings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as IndexRouteImport } from './routes/index'

const WeddingsRoute = WeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/marketing': typeof MarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/marketing': typeof MarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/marketing': typeof MarketingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weddings': typeof WeddingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commercial'
    | '/contact'
    | '/events'
    | '/marketing'
    | '/sitemap.xml'
    | '/weddings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commercial'
    | '/contact'
    | '/events'
    | '/marketing'
    | '/sitemap.xml'
    | '/weddings'
  id:
    | '__root__'
    | '/'
    | '/commercial'
    | '/contact'
    | '/events'
    | '/marketing'
    | '/sitemap.xml'
    | '/weddings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  MarketingRoute: typeof MarketingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingsRoute: typeof WeddingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weddings': {
      id: '/weddings'
      path: '/weddings'
      fullPath: '/weddings'
      preLoaderRoute: typeof WeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  MarketingRoute: MarketingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingsRoute: WeddingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
